# Generated by Django 5.1.6 on 2025-05-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_created_at_book_updated_at_readinggoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
