# Generated by Django 5.1.6 on 2025-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
