# Generated by Django 5.1.6 on 2025-06-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_book_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='api_book_status_cc2fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='api_book_created_2ad181_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['updated_at'], name='api_book_updated_efb88e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='api_book_categor_9ac228_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user'], name='api_book_user_id_7d51df_idx'),
        ),
    ]
