# Generated by Django 5.1.6 on 2025-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_category_book_api_book_status_cc2fe0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='custom_list',
        ),
        migrations.AddField(
            model_name='book',
            name='custom_lists',
            field=models.ManyToManyField(blank=True, related_name='books_m2m', to='api.customlist'),
        ),
    ]
